// <auto-generated />
namespace UdemySolid.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration_onee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_onee));
        
        string IMigrationMetadata.Id
        {
            get { return "202409071607252_migration_onee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
